receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 3s
    send_batch_size: 512

exporters:
  logging:
    loglevel: info
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: true
      job: true
      instance: true
      level: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, logging]
