spring:
  application:
    name: base-service
  datasource:
    url: jdbc:mysql://localhost:3306/secaml?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Asia/Shanghai
  cache:
    type: caffeine
  mvc:
    problemdetails:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3s

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix:
      logic-delete: true
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

security:
  jwt:
    issuer: example-auth
    secret: change-me-demo-secret-change-me-demo-secret
    access-token-ttl: 15m
    refresh-token-ttl: 30d
    max-refresh-token-per-user: 50

logging:
  level:
    com.example.base: off

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
