security:
  jwt:
    issuer: your-app
    access-ttl-seconds: 900
    refresh-ttl-seconds: 2592000
    key-id: k1
    # 建议使用真实 RSA PEM；未配置时会生成临时密钥（仅开发环境）
    public-key-pem: |
      -----BEGIN PUBLIC KEY-----
      ...
      -----END PUBLIC KEY-----
    private-key-pem: |
      -----BEGIN PRIVATE KEY-----
      ...
      -----END PRIVATE KEY-----
